language: ruby
rvm:
  - 2.3.1
script:
  - bash check.sh
  - cd hw3 && bundle install && bundle exec rspec spec

before_deploy:
  - pwd
  - ls
  - cd $TRAVIS_BUILD_DIR/hw3

deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: kottans-hw4
